version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: authix-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: authix_user
      POSTGRES_PASSWORD: authix_password
      POSTGRES_DB: authix
    volumes:
      - authix_pgdata:/var/lib/postgresql/data

volumes:
  authix_pgdata:
